name: Deploy Newstar to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - "newstar/**"
      - ".github/workflows/deploy-newstar.yml"
      - "README.md"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: newstar
    steps:
      - uses: actions/checkout@v3

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./newstar/dist
          destination_dir: projects/newstar
